### ISSUE TITLE
Docker Imageの権限を修正する

### ISSUE THREAD

**Issue by KanchiShimono** [KanchiShimono/spark-on-k8s-images#6]
## 事象

SparkSession取得時に`spark.jars.packages`オプションで外部パッケージを導入すると、処理実行時にエラーが発生する。

Driverノードにダウンロードされたjarをexecutorに配布する際にコピーエラーが発生している模様。

```java
java.nio.file.AccessDeniedException: ./org.mortbay.jetty_jetty-6.1.26.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:243)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$copyRecursive(Utils.scala:664)
	at org.apache.spark.util.Utils$.copyFile(Utils.scala:635)
	at org.apache.spark.util.Utils$.fetchFile(Utils.scala:502)
	at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$3.apply(Executor.scala:804)
	at org.apache.spark.executor.Executor$$anonfun$org$apache$spark$executor$Executor$$updateDependencies$3.apply(Executor.scala:801)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at org.apache.spark.executor.Executor.org$apache$spark$executor$Executor$$updateDependencies(Executor.scala:801)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:375)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## 対策

1. MasterとWorkerのSpark実行ユーザーを揃える
    - 現在はMasterがroot、Workerがuid=185で別のユーザーになっている
1. Workerの`SPARK_HOME`以下を777権限にする
    - こちらは動作確認済

## 参考

- https://stackoverflow.com/questions/50477893/file-access-error-running-spark-on-kubernetes

**Comment by KanchiShimono** [comment]
Jupyterはchmod 777で対応

https://github.com/jupyter/enterprise_gateway/issues/613
